# Generated by Django 3.2.18 on 2023-03-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, unique=True, verbose_name='number of question')),
                ('content', models.TextField(max_length=400, verbose_name='content of question')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['number'],
                'get_latest_by': 'number',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200, verbose_name='answer text')),
                ('descriptor_count', models.IntegerField(default=1, verbose_name='descriptor count number')),
                ('descriptor_increase', models.CharField(choices=[('EI', 'Orientation of consciousness'), ('SN', 'Orientation in the situation'), ('TF', 'The basis of decision-making'), ('JP', 'The method of preparing solutions')], max_length=50, verbose_name='descriptor type to increase')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='personality_test.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'answer option',
                'verbose_name_plural': 'answer options',
            },
        ),
    ]
